---
resource_types:
  - name: git-branches
    type: registry-image
    source:
      repository: aoldershaw/git-branches-resource

resources:
  - name: feature-branches
    type: git-branches
    source:
      uri: https://code.icb4dc0.de/prskr/goveal.git
      # The "(?P<name>pattern)" syntax defines a named capture group.
      # aoldershaw/git-branches-resource emits the value of each named capture
      # group under the `groups` key.
      #
      # e.g. feature/some-feature ==> {"groups": {"feature": "some-feature"}}
      branch_regex: '(\d+-|\w+\/)(?P<feature>.*)'

  - name: goveal.git
    type: git
    icon: github
    source:
      uri: https://code.icb4dc0.de/prskr/goveal.git
      fetch_tags: true

jobs:
  - name: set-feature-pipelines
    plan:
      - in_parallel:
        - get: feature-branches
          trigger: true
        - get: goveal.git
      - load_var: branches
        file: feature-branches/branches.json
      - across:
        - var: branch
          values: ((.:branches))
        set_pipeline: goveal-dev
        file: goveal.git/.concourse/branch-validate.yml
        instance_vars: {feature: ((.:branch.groups.feature))}
        vars: {branch: ((.:branch.name))}